version: '3'
services:
    frontend:
        build:
            context: .
            dockerfile: ./install/docker/frontend/Dockerfile
        ports:
            - "4200:4200"
    backend:
        build:
            context: .
            dockerfile: ./install/docker/backend/Dockerfile
        volumes:
            - ./backend:/app
        ports:
            - "5000:5000"
    redis:
        image: redis
        ports:
            - "6379:6379"
    celery:
        build:
            context: .
            dockerfile: ./install/docker/backend/Dockerfile.celery
            - "redis:redis"
